In [7]:
import pandas as pd
import numpy as py
import imageio as im
import os

In [35]:
maxFileWord = None
os.chdir = '/Users/rebec/Desktop/Python/a01/a01-000u'
for fileName in os.listdir(os.getcwd()):
    print (fileName)
    if maxFileWord == None:
        maxFileWord = fileName
        

.ipynb_checkpoints
a01
a01-000u-00-01.png
a01-000u.xml
a02
a02-000-00-00.png
a03
a04
a05
a06
b01
b02
b03
b04
b05
b06
c01
c02
c03
c04
c06
d01
d03
d04
d05
d06
d07
DATA NOTEBOOk.ipynb
e01
e02
e04
e06
e07
f01
f02
f03
f04
f07
g01
g02
g03
g04
g05
g06
g07
h01
h02
h04
h05
h06
h07
j01
j04
j06
j07
k01
k02
k03
k04
k07
l01
l03
l04
l07
m01
m02
m03
m04
m06
MiracleDataFile.xml
n01
n02
n03
n04
n06
p01
p02
p03
p06
r02
r03
r06
XML lets see if important


In [44]:
maxImage = None
mypath = '/Users/rebec/Desktop/Python/a01/a01-000u'

# stores all the of the files in the current path into the variable files
files = [ f for f in os.listdir(mypath) if os.path.isfile(os.path.join(mypath,f))]

images = py.empty(len(files), dtype=object)

for n in range(0, len(files)):
    images[n] = im.imread(os.path.join(mypath, files[n]))
    #print(images[n].shape)
    
maxImage = images[0]

for n in range(0, len(images)):
    if len(images[n]) > len(maxImage):
        maxImage = images [n];
    print (maxImage)

[[249 249 246 ... 251 251 251]
 [250 249 231 ... 251 251 251]
 [245 241 216 ... 251 251 251]
 ...
 [123 202 234 ...  94 194 233]
 [142 218 240 ... 158 230 241]
 [163 233 241 ... 221 237 242]]
[[249 249 246 ... 251 251 251]
 [250 249 231 ... 251 251 251]
 [245 241 216 ... 251 251 251]
 ...
 [123 202 234 ...  94 194 233]
 [142 218 240 ... 158 230 241]
 [163 233 241 ... 221 237 242]]
[[249 249 246 ... 251 251 251]
 [250 249 231 ... 251 251 251]
 [245 241 216 ... 251 251 251]
 ...
 [123 202 234 ...  94 194 233]
 [142 218 240 ... 158 230 241]
 [163 233 241 ... 221 237 242]]
[[255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [255 255 255 ... 251 249 251]
 [255 255 255 ... 251 251 251]
 [255 255 255 ... 251 251 251]]
[[255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [255 255 255 ... 251 249 251]
 [255 255 255 ... 251 251 251]
 [255 255 255 ... 251 251 251]]
[[255 255 255 ... 255 255 255]
 [255 255

# Padding the Images